### ISSUE TITLE
Why not use faster method?

### ISSUE THREAD

**Issue by btakita** [jonschlinkert/array-last#1]
```
function(ar) {
  return ar[ar.length-1];
}
```

**Comment by jonschlinkert** [comment]
hey @btakita good question. I did benchmarks when I created this but didn't commit them, so I went ahead and updated them and ended up improving the code as a result. so thanks for asking!

however, the function you suggested only gets the last element in an array, but we need to be able to slice a range of elements. Here are the benchmarks I created: https://github.com/jonschlinkert/array-last/blob/master/benchmark/last.md
